const mongoose = require('mongoose');

/**
 * Net Worth Snapshot Model
 * Periodic snapshots of user's assets and liabilities
 */
const netWorthSnapshotSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true
  },
  
  // Snapshot Date
  date: {
    type: Date,
    required: true,
    default: Date.now,
    index: true
  },
  period: {
    type: String,
    enum: ['daily', 'weekly', 'monthly', 'quarterly', 'yearly', 'manual'],
    default: 'monthly'
  },
  
  // Assets
  assets: {
    // Liquid Assets
    cash: {
      type: Number,
      default: 0
    },
    bankSavings: {
      type: Number,
      default: 0
    },
    bankCurrent: {
      type: Number,
      default: 0
    },
    
    // Investments
    stocks: {
      type: Number,
      default: 0
    },
    mutualFunds: {
      type: Number,
      default: 0
    },
    crypto: {
      type: Number,
      default: 0
    },
    bonds: {
      type: Number,
      default: 0
    },
    gold: {
      type: Number,
      default: 0
    },
    fixedDeposits: {
      type: Number,
      default: 0
    },
    ppf: {
      type: Number,
      default: 0
    },
    nps: {
      type: Number,
      default: 0
    },
    epf: {
      type: Number,
      default: 0
    },
    
    // Real Estate
    primaryHome: {
      type: Number,
      default: 0
    },
    rentalProperty: {
      type: Number,
      default: 0
    },
    land: {
      type: Number,
      default: 0
    },
    
    // Vehicles
    vehicles: {
      type: Number,
      default: 0
    },
    
    // Other Assets
    businessValue: {
      type: Number,
      default: 0
    },
    loansGiven: {
      type: Number,
      default: 0
    },
    otherAssets: {
      type: Number,
      default: 0
    },
    
    // Total
    totalAssets: {
      type: Number,
      default: 0
    }
  },
  
  // Liabilities
  liabilities: {
    // Loans
    homeLoan: {
      type: Number,
      default: 0
    },
    carLoan: {
      type: Number,
      default: 0
    },
    personalLoan: {
      type: Number,
      default: 0
    },
    educationLoan: {
      type: Number,
      default: 0
    },
    businessLoan: {
      type: Number,
      default: 0
    },
    
    // Credit Cards
    creditCardDues: {
      type: Number,
      default: 0
    },
    
    // Other
    emiOutstanding: {
      type: Number,
      default: 0
    },
    personalDebts: {
      type: Number,
      default: 0
    },
    otherLiabilities: {
      type: Number,
      default: 0
    },
    
    // Total
    totalLiabilities: {
      type: Number,
      default: 0
    }
  },
  
  // Net Worth
  netWorth: {
    type: Number,
    required: true
  },
  
  // Growth Metrics
  changeFromPrevious: {
    amount: {
      type: Number,
      default: 0
    },
    percentage: {
      type: Number,
      default: 0
    }
  },
  changeFromYearStart: {
    amount: {
      type: Number,
      default: 0
    },
    percentage: {
      type: Number,
      default: 0
    }
  },
  
  // Asset Allocation
  assetAllocation: {
    liquidAssets: {
      type: Number,
      default: 0
    },
    investments: {
      type: Number,
      default: 0
    },
    realEstate: {
      type: Number,
      default: 0
    },
    otherAssets: {
      type: Number,
      default: 0
    }
  },
  
  // Debt to Asset Ratio
  debtToAssetRatio: {
    type: Number,
    default: 0
  },
  
  // Liquidity Ratio
  liquidityRatio: {
    type: Number,
    default: 0
  },
  
  // Notes
  notes: {
    type: String
  },
  isAutoGenerated: {
    type: Boolean,
    default: true
  },
  
  // Metadata
  createdAt: {
    type: Date,
    default: Date.now
  },
  updatedAt: {
    type: Date,
    default: Date.now
  }
}, {
  timestamps: true
});

// Indexes
netWorthSnapshotSchema.index({ userId: 1, date: -1 });
netWorthSnapshotSchema.index({ userId: 1, period: 1, date: -1 });

// Methods
netWorthSnapshotSchema.methods.calculateTotals = function() {
  // Calculate total assets
  const assets = this.assets;
  this.assets.totalAssets = 
    (assets.cash || 0) +
    (assets.bankSavings || 0) +
    (assets.bankCurrent || 0) +
    (assets.stocks || 0) +
    (assets.mutualFunds || 0) +
    (assets.crypto || 0) +
    (assets.bonds || 0) +
    (assets.gold || 0) +
    (assets.fixedDeposits || 0) +
    (assets.ppf || 0) +
    (assets.nps || 0) +
    (assets.epf || 0) +
    (assets.primaryHome || 0) +
    (assets.rentalProperty || 0) +
    (assets.land || 0) +
    (assets.vehicles || 0) +
    (assets.businessValue || 0) +
    (assets.loansGiven || 0) +
    (assets.otherAssets || 0);
  
  // Calculate total liabilities
  const liabilities = this.liabilities;
  this.liabilities.totalLiabilities = 
    (liabilities.homeLoan || 0) +
    (liabilities.carLoan || 0) +
    (liabilities.personalLoan || 0) +
    (liabilities.educationLoan || 0) +
    (liabilities.businessLoan || 0) +
    (liabilities.creditCardDues || 0) +
    (liabilities.emiOutstanding || 0) +
    (liabilities.personalDebts || 0) +
    (liabilities.otherLiabilities || 0);
  
  // Calculate net worth
  this.netWorth = this.assets.totalAssets - this.liabilities.totalLiabilities;
  
  // Calculate ratios
  if (this.assets.totalAssets > 0) {
    this.debtToAssetRatio = (this.liabilities.totalLiabilities / this.assets.totalAssets * 100).toFixed(2);
  }
  
  const liquidAssets = (assets.cash || 0) + (assets.bankSavings || 0) + (assets.bankCurrent || 0);
  if (this.liabilities.totalLiabilities > 0) {
    this.liquidityRatio = (liquidAssets / this.liabilities.totalLiabilities).toFixed(2);
  }
  
  // Calculate asset allocation
  const totalAssets = this.assets.totalAssets;
  if (totalAssets > 0) {
    this.assetAllocation.liquidAssets = ((liquidAssets / totalAssets) * 100).toFixed(2);
    
    const investments = (assets.stocks || 0) + (assets.mutualFunds || 0) + (assets.crypto || 0) + 
                       (assets.bonds || 0) + (assets.gold || 0) + (assets.fixedDeposits || 0) +
                       (assets.ppf || 0) + (assets.nps || 0) + (assets.epf || 0);
    this.assetAllocation.investments = ((investments / totalAssets) * 100).toFixed(2);
    
    const realEstate = (assets.primaryHome || 0) + (assets.rentalProperty || 0) + (assets.land || 0);
    this.assetAllocation.realEstate = ((realEstate / totalAssets) * 100).toFixed(2);
    
    const otherAssets = (assets.vehicles || 0) + (assets.businessValue || 0) + 
                       (assets.loansGiven || 0) + (assets.otherAssets || 0);
    this.assetAllocation.otherAssets = ((otherAssets / totalAssets) * 100).toFixed(2);
  }
  
  return this;
};

netWorthSnapshotSchema.methods.calculateGrowth = async function() {
  // Get previous snapshot
  const previous = await this.constructor.findOne({
    userId: this.userId,
    date: { $lt: this.date }
  }).sort({ date: -1 });
  
  if (previous) {
    this.changeFromPrevious.amount = this.netWorth - previous.netWorth;
    this.changeFromPrevious.percentage = previous.netWorth !== 0
      ? ((this.changeFromPrevious.amount / previous.netWorth) * 100).toFixed(2)
      : 0;
  }
  
  // Get year start snapshot
  const yearStart = new Date(this.date.getFullYear(), 0, 1);
  const yearStartSnapshot = await this.constructor.findOne({
    userId: this.userId,
    date: { $gte: yearStart, $lt: this.date }
  }).sort({ date: 1 });
  
  if (yearStartSnapshot) {
    this.changeFromYearStart.amount = this.netWorth - yearStartSnapshot.netWorth;
    this.changeFromYearStart.percentage = yearStartSnapshot.netWorth !== 0
      ? ((this.changeFromYearStart.amount / yearStartSnapshot.netWorth) * 100).toFixed(2)
      : 0;
  }
  
  return this;
};

// Static methods
netWorthSnapshotSchema.statics.getLatest = async function(userId) {
  return await this.findOne({ userId }).sort({ date: -1 });
};

netWorthSnapshotSchema.statics.getHistory = async function(userId, months = 12) {
  const startDate = new Date();
  startDate.setMonth(startDate.getMonth() - months);
  
  return await this.find({
    userId,
    date: { $gte: startDate }
  }).sort({ date: 1 });
};

netWorthSnapshotSchema.statics.getTrend = async function(userId, period = 'monthly', count = 12) {
  const snapshots = await this.find({ userId, period })
    .sort({ date: -1 })
    .limit(count);
  
  return snapshots.reverse();
};

netWorthSnapshotSchema.statics.createFromCurrent = async function(userId) {
  const Investment = mongoose.model('Investment');
  const EMI = mongoose.model('EMI');
  const PersonalLoan = mongoose.model('PersonalLoan');
  const LenderLoan = mongoose.model('LenderLoan');
  const FinancialProfile = mongoose.model('FinancialProfile');
  
  // Get current investments
  const investments = await Investment.find({ userId, status: 'active' });
  
  // Get active loans/debts
  const emis = await EMI.find({ userId, status: 'active' });
  const personalLoans = await PersonalLoan.find({ userId, status: 'active' });
  
  // Get profile for bank balances
  const profile = await FinancialProfile.findOne({ userId });
  
  const snapshot = new this({
    userId,
    date: new Date(),
    period: 'manual'
  });
  
  // Calculate assets from investments
  investments.forEach(inv => {
    const value = inv.currentValue || 0;
    switch (inv.type) {
      case 'stock':
      case 'etf':
        snapshot.assets.stocks += value;
        break;
      case 'mutual_fund':
      case 'sip':
      case 'elss':
        snapshot.assets.mutualFunds += value;
        break;
      case 'crypto':
        snapshot.assets.crypto += value;
        break;
      case 'bond':
        snapshot.assets.bonds += value;
        break;
      case 'gold':
        snapshot.assets.gold += value;
        break;
      case 'fd':
      case 'rd':
        snapshot.assets.fixedDeposits += value;
        break;
      case 'ppf':
        snapshot.assets.ppf += value;
        break;
      case 'nps':
        snapshot.assets.nps += value;
        break;
    }
  });
  
  // Calculate liabilities from EMIs and loans
  emis.forEach(emi => {
    snapshot.liabilities.emiOutstanding += emi.remainingAmount || 0;
  });
  
  personalLoans.forEach(loan => {
    snapshot.liabilities.personalDebts += loan.outstandingAmount || 0;
  });
  
  // Calculate totals
  snapshot.calculateTotals();
  await snapshot.calculateGrowth();
  
  return await snapshot.save();
};

// Pre-save middleware
netWorthSnapshotSchema.pre('save', function(next) {
  this.updatedAt = new Date();
  this.calculateTotals();
  next();
});

const NetWorthSnapshot = mongoose.model('NetWorthSnapshot', netWorthSnapshotSchema);

module.exports = NetWorthSnapshot;
